android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official
android.uniquePackageNames=false
android.r8.strictFullModeForKeepRules=false
android.dependency.useConstraints=true
# Suppress the "excludeLibraryComponentsFromConstraints" performance hint (not needed at this project size)
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
